### ISSUE TITLE
Add a term for "strain"

### ISSUE THREAD

**Issue by cmungall** [phenoscape/taxrank#4]
There has been a request to add "strain" to NCBITaxon: 

- https://github.com/obophenotype/ncbitaxon/issues/107

I think the OBO NCBITaxon rendering should utilize URIs from taxrank

- https://github.com/obophenotype/ncbitaxon/issues/97

Is this in scope for taxrank?

**Comment by balhoff** [comment]
Sounds good to me. I don't think there is really a group of stakeholders to weigh in.

**Comment by hlapp** [comment]
Certainly in scope. The one caveat is that it hasn't been actively maintained for a while. However, taxonomic ranks aren't really changing all that much, so it's not obvious what kind of maintenance there could have been that wasn't.

**Comment by hlapp** [comment]
BTW, what's a little odd to me is that OLS doesn't show any hierarchy.

**Comment by balhoff** [comment]
> BTW, what's a little odd to me is that OLS doesn't show any hierarchy.

I don't think we have defined what the relationship is between ranks. Is_a would not be correct; maybe part_of but I'm not sure if there are exceptions.

**Comment by hlapp** [comment]
Ah yes, good point. The question is maybe would there be a problem with implying the presence of, say, some family for, say, every genus whether there's some nomenclatural code that defines that family or not.

**Comment by balhoff** [comment]
We could link them via skos as annotation properties, using e.g. `skos:broader`.

**Comment by hlapp** [comment]
We could, but I think that would run the risk of messing with search implementations, which may use `skos:broader` as a fallback for finding term matches.

**Comment by cthoyt** [comment]
see #5 for a more comprehensive update to this ontology based on ranks appearing in the NCBI Taxonomy database
